### ISSUE TITLE
JobsConfig

### ISSUE THREAD

**Issue by zKirki** [ChickensBurning/BlockKingdom#2]
Made prices a little low, or at least I think I did. Removed Explorer job because its a waste of space. Added double xp for jobs on Friday and Saturday nights from 8pm to 6am. Every jobs max level is 100 instead of 200. Did not touch xp and money multiplier because I did not know how much that could affect the incomes and experience of all of the jobs so I will leave that for you guys to tune up. 
[Jobs.zip](https://github.com/ChickensBurning/BlockKingdom/files/3423482/Jobs.zip)

**Comment by ChickensBurning** [comment]
Your changes have been implemented. Thank you for your help!
