### ISSUE TITLE
Slimefun Tailsman

### ISSUE THREAD

**Issue by SeantasticSean** [ChickensBurning/BlockKingdom#3]
Magical tailsman says that it grants you an additional enchantment while enchanting but does not actually do so. Occuring with an ender tailsman in ender chest.

**Comment by ChickensBurning** [comment]
Has this issue been fixed for you?

**Comment by SeantasticSean** [comment]
No still notifies you that you have been granted an additional enchantment but does not do so.

**Comment by ChickensBurning** [comment]
I have upgraded SlimeFun4 to the newest build. Is the issue resolved for you know?

**Comment by Sammy5k** [comment]
Talisman has been disabled for balancing purposes.
