### ISSUE TITLE
MyPets

### ISSUE THREAD

**Issue by ChickensBurning** [ChickensBurning/BlockKingdom#8]
Fully finish implementing MyPets for each of the various ranks.

The permission nodes will be added as follows:
Jade:
- Cow
- Pig
- Sheep

Garnet:
- Mooshroom
- Zombie
- Skeleton

Amethyst:
- Spider
- Wolf
- Blaze

Diamond:
- Baby Chicken
- Baby Cow
- Baby Sheep
- Baby Zombie
- Baby Pig

Sapphire:
- Stray 
- Rabbit
- Ocelot

Ruby:
- Snowman
- Donkey
- Horse
- Enderman
- Magma Cube

**Comment by jcbbosse** [comment]
Enhancement is done.
